### ISSUE TITLE
Not able to read the step definitions when the serenity js is added.

### ISSUE THREAD

**Issue by Rama9594** [jan-molak/serenity-js#102]
When i use the cucumber 3 with protractor and typescript. I is working fine.  Then i added the serenity js library into the config file. I am getting steps are undefined log message.

Please find the link below. https://stackoverflow.com/q/46792889/8779018

Please find where i am going wrong

**Comment by jan-molak** [comment]
Serenity/JS doesn't support Cucumber 3 just yet, but I'm planning to work on this shortly.
I'm also open to pull requests if anyone would like to help out.

**Comment by Rama9594** [comment]
Hi Jan, that is why I am using cucumber 1.3.3 or 1.3.2 version.
But when I run the cucumber tests the step definitions are not getting recognised. It's showing undefined implementation. I have tried with all the possibilities.

Please go throw the above link of stack overflow.  I have shared even the log file with config, feature, steps files and require files.

**Comment by jan-molak** [comment]
Ah OK, your original question mentions Cucumber 3, hence my response.

From what I can see in the examples in your [StackOverflow question](https://stackoverflow.com/questions/46792889/not-able-to-read-the-step-definitions-files-of-protractor-cucumber-e2e-tests) the problem is caused by the incorrect configuration of the feature files path. It doesn't seem to have anything to do with Serenity/JS, but I'll try to help you out regardless ;-)

So your project is stored under:
```
R:\protractor\protractorcucumber_typescript
```

You have a `protractor.conf.ts` file in that directory:

```
R:\protractor\protractorcucumber_typescript\protractor.conf.ts
```

And your feature files live under `features` here:

```
R:\protractor\protractorcucumber_typescript\features
```

That all makes perfect sense, but then in the `protractor.conf.ts` you state the following:

```typescript
    specs: ['./features/**/*.feature'],     // `./` is unnecessary here
    cucumberOpts: {
        require: ['/features/**/*Page.ts'], // the first slash incorrectly indicates the root directory, so R:\ in your case
        format: "pretty",
        compiler: "ts:ts-node/register",
    },
```

Instead, specify the path in the same way as in [the seed project](https://github.com/serenity-js/seed-cucumber/blob/master/protractor.conf.js), so:

```typescript
    specs: ['features/**/*.feature'],       // no `./`
    cucumberOpts: {
        require: ['features/**/*Page.ts'], // no forward slash at the beginning
        format: "pretty",
        compiler: "ts:ts-node/register",
    },
```

Hope that helps!
Jan
