### ISSUE TITLE
Installation help on Windows

### ISSUE THREAD

**Issue by rakeshnambiar** [jan-molak/serenity-js#206]
Hi, I am getting the below error while firing the 'npm install' command from \todomvc-protractor-cucumber-pageobjects folder. Using Win10 OS. Please advise. 

6865 warn serenity-protractor-cucumber-pageobjects@1.0.0 No repository field.
6866 verbose stack Error: serenity-js@0.0.1 postinstall: `lerna bootstrap --hoist && link-parent-bin`
6866 verbose stack Exit status 1
6866 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
6866 verbose stack     at emitTwo (events.js:126:13)
6866 verbose stack     at EventEmitter.emit (events.js:214:7)
6866 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
6866 verbose stack     at emitTwo (events.js:126:13)
6866 verbose stack     at ChildProcess.emit (events.js:214:7)
6866 verbose stack     at maybeClose (internal/child_process.js:925:16)
6866 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
6867 verbose pkgid serenity-js@0.0.1
6868 verbose cwd C:\Testcafe_demo\serenity-js\examples\todomvc-protractor-cucumber-pageobjects
6869 verbose Windows_NT 10.0.16299
6870 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
6871 verbose node v8.9.4
6872 verbose npm  v5.6.0
6873 error code ELIFECYCLE
6874 error errno 1
6875 error serenity-js@0.0.1 postinstall: `lerna bootstrap --hoist && link-parent-bin`
6875 error Exit status 1
6876 error Failed at the serenity-js@0.0.1 postinstall script.
6876 error This is probably not a problem with npm. There is likely additional logging output above.
6877 verbose exit [ 1, true ]

**Comment by marktigno** [comment]
It seems we have the same problem too. I attempted to build in on a Windows machine and encountering the same problems too. The only way to execute a build is to use a Linux or Mac OS machine.

**Comment by rakeshnambiar** [comment]
Are you sure it's worked in Mac OS? Because I had the same issue on my Mac Book and switched to the windows machine after that.

**Comment by jan-molak** [comment]
Hey @rakeshnambiar and welcome to the Serenity/JS community :-) 

Did you run `npm install` in the root directory before installing the dependencies of that example project? 

Jan

**Comment by rakeshnambiar** [comment]
thanks @jan-molak  
Yes, I tried 'npm install' command from ' \todomvc-protractor-cucumber-pageobjects' directory.

**Comment by rakeshnambiar** [comment]
@jan-molak did you get a chance to look into this, please?

**Comment by jan-molak** [comment]
Hey @rakeshnambiar! `todomvc-protractor-cucumber-pageobjects` [relies on the local, source](https://github.com/jan-molak/serenity-js/blob/master/examples/todomvc-protractor-cucumber-pageobjects/package.json#L30) of `serenity-js`, rather than the npm version. This means that if you want to actually execute those examples you'll need to build serenity-js from source:

```
git clone https://github.com/jan-molak/serenity-js.git
cd serenity-js
npm install                              # this installs the dependencies of serenity-js modules
npm run verify                           # this compiles serenity-js and runs the tests

cd examples/todomvc-protractor-cucumber-pageobjects
npm install                              # installs the dependencies of the example project
npm test                                 # runs the tests in the example project
```

Alternatively, you can replace the following entry in `todomvc-protractor-cucumber-pageobjects/package.json`:
```
    "serenity-js": "file:../../"
```
with:
```
    "serenity-js": "^1.10.12"
```
This will make the example project rely on the latest _published_ version of Serenity/JS.

With that in place you can simply run the below command from the example project directory.
```
npm install 
npm test
```

Does that help?
Jan

**Comment by rakeshnambiar** [comment]
Dear @jan-molak thanks a lot for the detailed explanation. I followed your steps and successfully executed the tests on OS X. Regarding the Windows OS, I will check and update you on Monday.

<img width="546" alt="screen shot 2018-04-28 at 9 59 05 pm" src="https://user-images.githubusercontent.com/20258636/39400833-d3cd4500-4b2f-11e8-859a-1d562b62b43e.png">

**Comment by rakeshnambiar** [comment]
Hi @jan-molak another query regarding the setup 

As far as I know the IntelliJ IDEA community version doesn't support JavaScript or TypeScript. Could you please suggest an alternative (which supports Cucumber and JavaScript together)?

Thanks in advance.

**Comment by rakeshnambiar** [comment]
@jan-molak - Could you please help also on the below.

I am can navigate to the step definition from IntelliJ IDEA, however when I try to execute the individual test through right click, the IDE unable to locate the JavaScript steps.  Only option to execute the test is through the Terminal. Could you please advise how do I change the folder structure to resolve this issue?

**Comment by jan-molak** [comment]
Hi @rakeshnambiar, I hear that [Visual Studio Code](https://code.visualstudio.com/) has very good support for JavaScript and TypeScript. I haven't used it much myself, so would be glad to hear about your experience.

**Comment by jdmesalosada** [comment]
Hi @rakeshnambiar in order to execute a specific feature you can go to Debug option,  select Add Configuration, and put the following code:

{
// Use IntelliSense to learn about possible Node.js debug attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "launch",
"name": "Launch Program",
"program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
"args": [
"${workspaceRoot}/protractor.conf.js",
"--cucumberOpts.name",
"here goes the scenario name to debug"
]
}
]
}

And then you can do  Debug -> start debugging.

Let me know if that helps.

**Comment by rakeshnambiar** [comment]
dear @jdmesalosada, @jan-molak many thanks for your help.

I am getting the below error in both Visual Studio and IntelliJ. Not sure what setting I missed.

[21:30:32] I/launcher - Running 1 instances of WebDriver
logger.js:154
[21:30:32] I/testLogger - 
logger.js:154
------------------------------------
[21:30:32] I/testLogger - [chrome #01-0] PID: 4681
logger.js:154
[chrome #01-0] 
[chrome #01-0] Starting inspector on 127.0.0.1:30245 failed: address already in use
