### ISSUE TITLE
is there a way to adopt a REST library into my serenity-js environment?

### ISSUE THREAD

**Issue by kdp88** [jan-molak/serenity-js#207]
is there a way to adopt a REST library into my serenity environment?

**Comment by kdp88** [comment]
@san-ouadghiri  

how would I go about grabbing data from a post request
using the example you provided I have (hopefully done something right):

```
//feature file
 Given that I am a new authenticated user
    When I ask for the new tenant Id
    Then that I am a new authenticated user
```
```
//steps file
this.Given(/^.*that (.*) am a new authenticated user$/, name => {
    return stage.theActorCalled(name).attemptsTo(
      Post.item({ email: 'email@email.com', password: 'test1234'}).on('/v1/login'),
    );
  });
```
my intention in the `this.When` is to get me the data back
```
//steps file
this.When(/^(.*) ask for the new tenant Id$/, name => {
    return stage.theActorCalled(name).attemptsTo(
      AskForASpecificTenantId(),
    );
  });
```

this is where i get stuck because it doesnt work and im pretty sure im not doing it right

any ideas?

**Comment by san-ouadghiri** [comment]
Your super clear :+1: . And there's certainly a way to do it. However (sorry) I haven't experiment that yet. Plus I'm no cucumber user so I can't provide with any example. If I move on on my own axios integration, I'll let you know about my findings.

**Comment by jan-molak** [comment]
As per our conversation on #130:

```typescript
import { CallAnApi, LastResponse, Post } from '@serenity-js/rest';
import { Actor } from '@serenity-js/core';

const Bob = Actor.named('Bob').whoCan(CallAnApi.at('https://yourdomain.com/api'));

Bob.attemptsTo(
  Post.item({ name: 'iPod' }).on('/basket'),
  See.if(LastResponse(), res => expect(res.status).to.eventually.equal(200)),
);
```

`LastResponse()` is a `Question` that gives you access to the, well, last response :-)

## CQRS

The way I like to think about this is that Serenity/JS implements a flavour of the command/query responsibility segregation pattern.

Tasks and Interactions (such as `Click` or `Post`) are your "commands" - they change the state of the system under test.

Questions (such as `LastResponse()`, `Text.of()`, etc.) are your queries - they retrieve certain aspects of the system's state so that you can assert on them.

This means that in order to perform an action and then assert on the result of that action you'll always need a Task/Question combo:

```typescript
Bob.attemptsTo(
  Post.item({ name: 'iPod' }).on('/basket'),
  See.if(LastResponse(), res => expect(res.status).to.eventually.equal(200)),
);
```

If you're not familiar with `See.if` - it's a special kind of interaction - it takes a `Question`, resolves it, and passes on to the assertion.

Another nice thing you can do about those assertions  that you use often is that you can extract them into domain-specific assertion functions, for example:

```typescript

const response = {
  statusEquals: (statusCode: number) => (response) => expect(response.status).to.eventually.equal(statusCode),
  dataDeepEquals: (expected: any) => (response) => expect(response.data).to.eventually.deep.equal(expected),
}

Bob.attemptsTo(
  Post.item({ name: 'iPod' }).on('/basket'),
  See.if(LastResponse(), response.statusEquals(200)),
  See.if(LastResponse(), response.dataDeepEquals({ status: 'purchase confirmed' })),
);
```

Hope that helps!
Jan

**Comment by kdp88** [comment]
@jan-molak Thanks a ton, very thorough explanation I guess my disconnect is that these examples are perfect when I am expecting a response status to equal x status but what about the event when I the user needs to get an auth token back from the API and I `Post.item`  and want to store `{"accessToken": "2e2e2e"...}` in a variable to use on another `Post.item`? Maybe I am the 1 % that would like to see this example

**Comment by jan-molak** [comment]
Haha, not at all! In this case, you might need something a bit more advanced. It really does depend on the API you're testing, though. For example - do you need a token for every single request, or do you get one to perform several requests? What happens if you request the token more than once? Would you invalidate other tokens that have already been issued, which could make running parallel tests problematic? There are quite a few considerations here, as I'm sure you're well aware.

There's a number of ways you could go about implementing this. One way to do it could be to make the remembering of the token the responsibility of the `Ability`. If that's the design you like, you could use [`CallAnApi`](https://github.com/jan-molak/serenity-js/blob/87fa2c1249e1e2db24015ffe7dfec1b39ebfbf54/packages/rest/src/screenplay/abilities/call_an_api.ts) as the foundation. For example:
```typescript

class SecurelyCallAnApi extends CallAnApi {
    // we augment the interface to add a private field to store the token
    // which ensures that each actor gets their own token
    private token: string;

    // and a method to authenticate us and store the token
    authenticateWith(apiKey: string) {  // key, credentials, cert, etc...
        return this.get(`/token/${ apiKey }`).then(res => {
            this.token = res.data.token;  // or something like this
        })
    }

    // then we override the remaining methods that require the token, for example
    post(url: string, data?: any, config?: AxiosRequestConfig): PromiseLike<AxiosResponse> {
        return super.post(url, data, Object.assign({}, 
            { headers: { 'X-TOKEN': this.token } }, // if the token is passed in as a header
            config,                                 // we can augment the axios config, for example
        ))
    }

    // ... other methods follow the same pattern, omitted for brevity
}
```

With this in place you can add a couple of `Interaction`s to match the original `@serenity-js/rest` module, but using the `SecurelyCallAnApi` instead of the base `CallAnApi`. For example:

```typescript
const AuthenticateWith = (apiKey: string) => Interaction.where(`#actor authenticates with key: ${ apiKey }`, 
    actor => SecurelyCallAnApi.as(actor).authenticateWith(apiKey),
);

const Post = (item: any) => ({ on: (resource: string) => Interaction.where(
    `#actor executes a POST on resource ${ resource } with item: ${ item }`,
    actor => SecurelyCallAnApi.as(actor).post(resource, item),
);

// and so on, Get and others omitted for brevity
```

With the above in place you can teach your actor to interact with the secure API:

```typescript
const Simon = Actor.named('Simon').whoCan(SecurelyCallAnApi.at('https://my.org/api'))

Simon.attemptsTo(
    AuthenticateWith('some-api-key'),     // this interaction stores the token on the ability
    Post({ some: 'item' }).on('/basket'), // that's your custom Post, rather than the built-in one
);
```

Other ways to do it could, for example, include:
- making the custom ability lazy-load the token, so upon the first call to get/post/put, etc you check if you have the token and request it if you don't
- creating custom interactions (Get/Post/Put, etc) that request the token and cache it within the interaction scope instead of a custom ability - this helps you avoid having to implement your own ability

Does this help?

Jan

**Comment by kdp88** [comment]
@jan-molak 

this is promising, I am going to test this tomorrow, you are one hell of a dude! 
![not-worthy](https://user-images.githubusercontent.com/12736081/39794181-08e6619c-5317-11e8-8716-0e163adb533b.gif)

**Comment by marktigno** [comment]
Hello @jan-molak,

Need help on this one, I've already imported already the objects from '@serenity-js/rest' but it seems it cannot find the "status" property. Am I doing something wrong on my end? Thanks!
![image](https://user-images.githubusercontent.com/13494822/39854381-0d7958ba-545a-11e8-906d-3bad7b6ae034.png)

**Comment by kdp88** [comment]
@jan-molak  

take a look at this error
this image is extracted straight from your response above
![image](https://user-images.githubusercontent.com/12736081/39871100-cafb5858-5431-11e8-9a93-a082f650e191.png)

here is the super function called `post` from `CallAnApi`

```
/**
     * Call the api method post on the url.
     * Response will be resolved and made available as lastResponse.
     *
     * @param {string} url
     * @param data
     * @param {AxiosRequestConfig} config
     * @returns {PromiseLike<void>}
     */
    post(url: string, data?: any, config?: AxiosRequestConfig): PromiseLike<AxiosResponse> {
        return this.axiosInstance.post(url, data, config).then(
            fulfilled => this.lastResponse = fulfilled,
            rejected => this.lastResponse = rejected.response,
        );
    }
```
I think im confused on why I am getting this error

**Comment by kdp88** [comment]
@marktigno 
we got that same error, we solved that by creating a question 

```
//response-messages.ts
export const ResponseMessage = () => Question.about(`The Response Message`, actor =>
  CallAnApi.as(actor).getLastResponse() as PromiseLike<AxiosResponse>,
);

export const hasResponseCode = id => question => question.then(lastResponse => expect(lastResponse.status).to.equal(id));
```

`//steps file`
```
this.Given(/^.*that (.*) am a new authenticated user$/, name => {
    return stage.theActorCalled(name).attemptsTo(
      See.if(ResponseMessage(), hasResponseCode(200)),
    );
  });
```

**Comment by jan-molak** [comment]
That's a good way to do it, @marktigno. You can also have a question that retrieves a specific part of the response, for example:

```typescript
export const LastResponseStatus = () => Question.about(`last response status`, actor =>
  CallAnApi.as(actor).getLastResponse().then(response => response.status),
);
```
```typescript
// assertions.ts
export const equals = (expected: number) => (actual: number) =>
    expect(actual).to.eventually.equal(expected);
```

```typescript
// steps.ts
this.Then(/^(.*) has authenticated correctly$/, name => stage.theActorCalled(name).attemptsTo(
    See.if(LastResponseStatus(), equals(200)),
));
```

**Comment by marktigno** [comment]
Hello @jan-molak and @kdp88,
This is awesome guys, now I'm finally to get now working here on my end. Thanks! :)

**Comment by kdp88** [comment]
@jan-molak  and @marktigno 
We did end up getting POST to work with authentication (auth to get the token and store it inside the header for POST) but struggling with deleting the ID as its a private property inside a class that the steps cant extract out... take look.... thoughts comments ??

using the same exact examples Jan provided earlier `(post(url: string, data?: any, config?: AxiosRequestConfig):)` in this thread we added a few more functions and tweaked some things:

```
//securely-call-api.ts
export class SecurelyCallAnApi extends CallAnApi {
  private token: string;
  private tenantId: string;
  private createdAccountId: string;

constructor(private axiosInstance: AxiosInstance) {
    super(axiosInstance);
  }

  static as(actor: UsesAbilities): SecurelyCallAnApi {
    return actor.abilityTo(SecurelyCallAnApi);
  }

  static at(baseURL: string) {
    const axiosInstance: AxiosInstance = axios.create({
      baseURL,
      timeout: 2000,
      headers: { Accept: 'application/json,application/xml' },
    });
    return new SecurelyCallAnApi(axiosInstance);
  }

//authenticate
authenticateWith(uEmail: string, uPassword: string) {
    const data = { email: uEmail, password: uPassword};
    return this.post(`/v1/login`, data).then(res => {
      this.token = res.data.accessToken;
      let tenantId;
      for (let i = 0; i < res.data.tenants.length; i++) {
        if (res.data.tenants[i].tenantName === 'Test Environment') {
          tenantId = res.data.tenants[i].tenantId;
        }
      }
      this.tenantId = tenantId;
      console.log('tenantId', this.tenantId);
      console.log('AUTH TOKEN', this.token);
    });
  }

//post
createAccountWith(accountData: object) {
    const data = accountData ;
    const url = `your_URL`;
    return this.post(url, data).then(res => {
      console.log('I CREATED THE ACCOUNT WITH STATUS------------', res.status);
      this.createdAccountId = res.data.accountId;
      console.log('accountid', res.data.accountId);
    });
  }

//had to override the delete from callAnpi
delete(url: string, config?: AxiosRequestConfig): PromiseLike<AxiosResponse> {
    if (this.token) {
      return super.delete(url, Object.assign({},
        { headers: { 'X-Billtrust-Auth': this.token } },
        config,
      ));
    } else {
      return super.delete(url);
    }
  }
```

In another file we have 

```
export const AuthenticateWith = (email: string, password: string) => Interaction
    .where(`#actor authenticates with creds: ${ email },${ password }`,
  actor => SecurelyCallAnApi.as(actor).authenticateWith(email, password)
);

export const CreateAccountWith = (data: any) => Interaction
      .where(`#actor creates account with ${ data }`,
    actor => SecurelyCallAnApi.as(actor).createAccountWith(data)
  );

export const DeleteAccountWith = (accountId: string) => Interaction
  .where(`#actor deletes account with ${ accountId }`,
    actor => SecurelyCallAnApi.as(actor).deleteAccountWith(accountId)
  );
```
```
//steps file
this.Given(/^.*that (.*) have created a new account$/, () => {
    return stage.theActorCalled(name).attemptsTo(
      AuthenticateWith('test@test.com', 'myPassword!'),
      CreateAccountWith(
        {
        'test1': '989898',
        'test2': 'f3',
        'test3': 'Active',
        'test4': 'AUTOMATION',
          'test5': [
            {
              'inner1': 'afafadsfasdf',
              'inner2': 'asdfasdf',
              'inner3': 'afasfasdf',
              'inner4': 'asdfasdf',
              'inner5': 'asdfasdf',
              'inner6': 'asdfasdf',
              'inner7': 'adfasdf',
              'inner8': 'adfasdf',
              'inner9': 'sfadsfa'
            }
          ],
      }),
    );
  });
```

**Comment by jan-molak** [comment]
Linking with #208

**Comment by abhinaba1080** [comment]
Hi @jan-molak 

Keeping REST related queries in the same ticket... **Need help Badly**

Stack: TS , Serenity (1.x), Axios

**Scenario flow:**

1. Post user information to API1 (Working)
2. Get the authentication token (Working)
3. Now, with the token send a POST request to another API (Working)
4. Get LastResponse and validate it (Not Working)

**Issue Observed:** LastResponse() working fine while getting the response from API1 but, after Posting to API2, LatsResponse() is coming as undefined.  Strangely, in case of invalid responses (400, 500 etc..) from API2, we are getting the valid LastResponse, the issue is only observed for 200 valid response.

Is this happening because of the promise/wait in case of valid response?
