### ISSUE TITLE
REST API Testing with Chakram

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#237]
Hello! Any idea how to integrate Chakram on SerenityJS? I'm trying to do REST API testing using this: http://dareid.github.io/chakram/

**Comment by jan-molak** [comment]
Chakram looks cool :-) You'd need to implement something similar to [@serenity-js/rest](https://github.com/jan-molak/serenity-js/tree/master/packages/rest/src/screenplay), so:
- an `Ability` wrapping the `chakram` object and exposing methods like `get` or `post`
- a bunch of `Interactions` so that you can use the above `Ability` in the `Actor` flow.
- you'll also need some `Questions`, akin to `LastResponse` to extract the response returned by `chakram` in the `See.if(..., ...)` task

Does that help?

**Comment by marktigno** [comment]
Hello @jan-molak,
Sure will try on this, I'm having a hard time trying REST testing using the built-in one on SerenityJS but I'll give a shot on this. Thanks!

**Comment by jan-molak** [comment]
Yeah, REST testing needs some love; especially around documentation and reporting... and probably a video course...

Let me know how you're getting on!
