### ISSUE TITLE
Issue with Scenario Outline example

### ISSUE THREAD

**Issue by AbhineetSharmax** [jan-molak/serenity-js#248]
After finishing one example, it throws error. Asynchronous timeout.

Wanted to close the browser for each example and open next example in a new fresh browser.
Is there any way to instantiate browser for every example?

**Comment by jan-molak** [comment]
Hi @AbhineetSharmax! 

It's hard to tell why the test is experiencing a timeout without seeing the code... To answer your question - [Protractor](https://github.com/angular/protractor) is in control of the browser session, so in order to restart the browser you'll need to set `restartBrowserBetweenTests` to `true` in the [`protractor.conf.js`](https://github.com/angular/protractor/blob/249e657baa605257c268f09078d56219776db9b1/lib/config.ts#L538);

Please bear in mind that restarting the browser can significantly affect the amount of time it takes to run a test, so you might need to consider an alternative such as clearing any state that might hang around in the browser after a test instead - clear the coookies, clear local storage, etc.

Hope this helps!
Jan
