### ISSUE TITLE
Timing issue with 2 select steps

### ISSUE THREAD

**Issue by BrendanDougan** [jan-molak/serenity-js#27]
Hi, 

I'm calling 2 steps in my feature which pick values from a select box using a task which uses Select.theValue(..).from(..)

The 2nd value doesn't get chosen. If I repeat the step 10 times, it does get chosen, leading me to think it's a timing issue. Similarly if I omit the first step and use the 2nd on it's own, it works as expected.

Any ideas?

**Comment by jan-molak** [comment]
Hello there!

Would you be able to reproduce the issue in a test case such as one of [those here](https://github.com/jan-molak/serenity-js/blob/master/spec/cookbook/html_form.recipe.ts)?

Thanks,
Jan

**Comment by srinivasbudh** [comment]
@BrendanDougan,

I'm not really sure of the root cause but i did faced it several times using different tools and frameworks, you can try below work around's which might help.

**1st workaround (this can be used if its a form with other details to enter just change the order):**

**example:**
![image](https://cloud.githubusercontent.com/assets/24290981/23016871/6781a39a-f438-11e6-8826-6dcb400b8965.png)

**In between entering the values in the drop downs, you can enter the value in input feild's or select a radio button like below**
Select.theValue(..).from(..),
Enter.theValue(..).into(..),
Enter.theValue(..).into(..),
Select.theValue(..).from(..)

**2nd workaround (this can be used if there are only 2 dropdown boxes to select from):**

**example:**
![image](https://cloud.githubusercontent.com/assets/24290981/23016981/c1676fa2-f438-11e6-88d3-8d254fea6f74.png)

**If you have no other option to select in between 2 drop downs you can wait for a while before selecting the value from second drop down.**
Select.theValue(..).from(..),
Wait.for(Duration.ofSeconds(..)),
Select.theValue(..).from(..)


**Please ignore this message if this is not appropriate to your issue**

**Comment by BrendanDougan** [comment]
@srinivasbudh 
Thanks for that
`Select.theValue(..).from(..),
Wait.for(Duration.ofSeconds(..))`
in my task has fixed the issue

@jan-molak 
I'll try and put a test together if I have some free time. Cheers

**Comment by jan-molak** [comment]
Waiting for elements to appear as well as waiting for a specific amount of time is now [demonstrated here](https://github.com/jan-molak/serenity-js/blob/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/spec/cookbook/waiting.recipe.ts#L91)
