### ISSUE TITLE
import { protractor } from 'protractor'; in serenityJS guide

### ISSUE THREAD

**Issue by tremkonzah** [jan-molak/serenity-js#3]
Hello, 

i have update to serenity-js 0.6.2, when i type this

```
// features/step_definitions/todo_user.steps.ts

import { protractor } from 'protractor';

// ...

export = function todoUserSteps() {

    let actor: Actor;

    this.Given(/^.*that (.*) has a todo list containing (.*)$/, (actorName: string, items: string) => {

        actor = Actor.named(actorName).whoCan(BrowseTheWeb.using(protractor.browser));
```

got an error Unresolved variable browser.

and i should use `import { protractor } from 'protractor/built';` and its works.

something wrong with my code or the guide?

**Comment by jan-molak** [comment]
What version of protractor are you using?

**Comment by tremkonzah** [comment]
using protractor 4.0.11 as per serenity-js 0.6.2
```
node node_modules/protractor/bin/protractor --version
Version 4.0.11
```

**Comment by jan-molak** [comment]
Looks like the [tutorial project](https://github.com/jan-molak/serenity-js-getting-started) was stuck using protractor 4.0.4 (where the `protractor` object lives under `protractor/globals` and `protractor/built`) rather than the latest version - 4.0.11, where it's in the `protractor` package.

I've updated the tutorial project so that it uses the correct version.

(If you've already installed the node modules and have protractor 4.0.4 in the `node_modules` directory you'll need to delete it before running `npm install` for the new version to be installed correctly).

Please let me know how you got on. Thanks for helping me get the documentation perfect 👍 

J

**Comment by tremkonzah** [comment]
Thanks, works perfectly after update

**Comment by jan-molak** [comment]
Excellent, thanks for letting me know :-)
