### ISSUE TITLE
"eventually not a property of Assertion" error

### ISSUE THREAD

**Issue by johnlister** [jan-molak/serenity-js#30]
While trying to run the tests (using the 2-reports branch). I get the following error:

[14:27:57] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
features\step_definitions\todo_user.steps.ts (31,14): Property 'eventually' does not exist on type 'Assertion'. (2339)
    at getOutput (C:\src\js\tutorial-from-scripts-to-serenity\node_modules\ts-node\src\index.ts:312:17)
    at C:\src\js\tutorial-from-scripts-to-serenity\node_modules\ts-node\src\index.ts:343:18
    at Object.compile (C:\src\js\tutorial-from-scripts-to-serenity\node_modules\ts-node\src\index.ts:476:19)
    at Module.m._compile (C:\src\js\tutorial-from-scripts-to-serenity\node_modules\ts-node\src\index.ts:406:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\src\js\tutorial-from-scripts-to-serenity\node_modules\ts-node\src\index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

It appears that either "chai as promises" isn't being setup properly or there is a typescript issue.

using node 6.10 and npm 4.4.1.

Am I missing something obvious?

**Comment by jan-molak** [comment]
Thanks for reporting this, that's interesting.

Are you seeing this problem on a fresh copy of `2-reports`?

**Comment by marktigno** [comment]
Actually I'm also experiencing the same error when I'm creating my scripts using Screenplay pattern. I just follow what is instructed on the tutorial but that TSError (2339) always appearing.

**Comment by jan-molak** [comment]
Sorry to hear that, what platform are you on? OS/node version?

Also, @johnlister and @marktigno would you be able to push the code to github so that I can try to reproduce the problem?

**Comment by marktigno** [comment]
@jan-molak Here's what I used on my machine:
OS: Windows 10
Node: 6

I used npm manager to pull a fresh copy of the packages, but the problem is on the chai-as-promise part where it says the "eventually" is not recognized as part of 'Assertion'. I check the exports from the 'expect.ts' file on the sample project to see if the references are properly set, but it seems there is missing on it.

**Comment by johnlister** [comment]
Windows 10, fresh install of Node 6.10, updated to latest NPM (4.4). clone the tutorial and switch to "2-reports" branch
npm install followed by npm test.  This is with unmodified code in the branch.

I haven't installed any npm modules globally - oddly visual studio code doesn't complain about eventually, but does note that expect returns the base Assertion class and not a PromiseAssertion. I'm reasonably new to typescript, but is this a types issue in how it interprets the response of expect?

**Comment by marktigno** [comment]
Here's my sample screenshot:

![image](https://cloud.githubusercontent.com/assets/13494822/23911542/1e84dd2a-0918-11e7-8b24-c4f39cdddf3d.png)

**Comment by jan-molak** [comment]
I see what you mean, but I'm not able to reproduce the issue on a MacOS and don't have access to a Windows machine at the moment. There are several things at play here, so maybe this will help you find out more about the root cause of the problem:

- [`chai-as-promised`](https://github.com/domenic/chai-as-promised) is a JavaScript library, so it needs external type definitions - `@types/chai-as-promised`
- [`@types/chai-as-promised`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/264c29142589d25f87f2d3e4144c0426f1ba4c63/chai-as-promised) [augments the interface](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/264c29142589d25f87f2d3e4144c0426f1ba4c63/chai-as-promised/index.d.ts#L18) of the standard chai assertion to add the `eventually` property

For `chai-as-promised` to work with `chai`, we need to:
- [register it](https://github.com/serenity-js/tutorial-from-scripts-to-serenity/blob/d880bd28407c55806c4c3054f52904aae4c32000/spec/expect.ts#L3)
- but we also need to make the IDE aware of the type definitions (as far as IntelliJ or VisualStudio are concerned, it's still regular Chai that they're providing intelli-sense for, that's why they complain about the property not being there)

My IntelliJ is configured to use the local TypeScript module and the `tsconfig.json` file that ships with the tutorial:
<img width="833" alt="screen shot 2017-03-14 at 16 46 38" src="https://cloud.githubusercontent.com/assets/1089173/23911850/f4271364-08d5-11e7-897a-86021f92d83a.png">

I'm guessing that VS might need similar sort of configuration.

**Comment by johnlister** [comment]
Visual Studio Code seems to work fine, it seems to be the just in time compilation when it loads the web page or test within?

**Comment by marktigno** [comment]
I did a little play around on the "node_modules/@types/chai/index.d.ts" and place the line "eventually: Assertion;". Now it recognized the keyword but it gives now a different error shown here:

![capture](https://cloud.githubusercontent.com/assets/13494822/23932558/c5ac5df2-0973-11e7-90dd-e2aeca499f31.PNG)

**Comment by marktigno** [comment]
I found the solution here:
https://github.com/jan-molak/serenity-js-fast-track-demo/commit/1b545fa450d83bf5689c119107fb804438e09d7e

**Comment by johnlister** [comment]
Perfect, works for me. Oddly google didn't bring that up, but I did spot something similar in another project. I incorrectly assumed that both forms were identical in function - clearly not.

**Comment by jan-molak** [comment]
Hey @johnlister @marktigno, I've just updated the tutorial, would you mind checking if that helps to solve the problem you noticed?

**Comment by marktigno** [comment]
@jan-molak will do, I'll apply the latest updates on my local machine and verify the fix.

**Comment by marktigno** [comment]
Hello @jan-molak, I've verified the fix and now it's working. However there's a separate issue when running the test. It seems it's getting a timeout issue after it's launch. But I've made another fix on it so it won't happened again.

![helpers-1](https://cloud.githubusercontent.com/assets/13494822/24088504/12f8075a-0d66-11e7-8de0-415dcc885d8e.PNG)

![helpers-2](https://cloud.githubusercontent.com/assets/13494822/24088506/1bc97968-0d66-11e7-85b8-fd89812b51e2.PNG)

Thanks! :)

**Comment by jan-molak** [comment]
No problem at all! The todomvc.com website can be slow at times, so setting the timeout will definitely help :-)

**Comment by johnlister** [comment]
So the fix you've put in place works, but there is an issue on the dependency of gherkin. It now fetches v4.1.1 of gherkin (via cucumber) which when I run it causes the following issue:

```
E/launcher - Error: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:539:5)
    at C:\src\js\serenity-js-e2e-testing-sample\node_modules\serenity-js\src\serenity\reporting\serenity_bdd_reporter.ts:89:38
```

Forcing gherkin to be v4.0.0 works - it looks like the only difference is gherkin has updated to using node 7 - I suspect the path api has changed as I'm currently running node 6.10

**Comment by jan-molak** [comment]
Thanks @johnlister, @metrophos has just raised that under #32

**Comment by marktigno** [comment]
Hello @jan-molak!
I've updated the package.json based on what is posted on issue #32 and it works perfectly. Thanks!

**Comment by jan-molak** [comment]
Perfect, thanks for the update :-)

**Comment by rollrodrig** [comment]
I have the same problem. I am using docker.
simple function

`let funcPromise = (n) => {
    return new Promise((resolve, reject) =>{
        if(n=="a") {
            resolve("success");
        }else {
            // throw new Error("bad");
            reject("Fail")
        }
    })
}`

simple test

`expect(func).to.eventually.equal("success");`


Error on terminal
`FileTest.spec.ts:43:25 - error TS2339: Property 'eventually' does not exist on type 'Assertion'.`

**Comment by jan-molak** [comment]
Hi @rollrodrig,

At first glance, the reason behind the compiler error seems to be the mixup of different import styles.

Instead of saying:
```typescript
import chai from 'chai';
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
let expect = chai.expect;
let assert = chai.assert;
```
Try:
```typescript
import chai = require('chai');
import chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

const expect = chai.expect;
```

The `var chaiAsPromised = require('chai-as-promised')` syntax tells the compiler that the module in question does not have any type definitions. Because of that, `chai-as-promised` types are never registered, and the compiler correctly complains that `Property 'eventually' does not exist on type 'Assertion'`, as both `eventually` and `rejected` are defined in the `chai-as-promised` module which has been ignored.

Hope this helps!
Jan

**Comment by rollrodrig** [comment]
> Hi @rollrodrig,
> 
> At first glance, the reason behind the compiler error seems to be the mixup of different import styles.
> 
> Instead of saying:
> 
> ```ts
> import chai from 'chai';
> var chaiAsPromised = require('chai-as-promised');
> chai.use(chaiAsPromised);
> let expect = chai.expect;
> let assert = chai.assert;
> ```
> 
> Try:
> 
> ```ts
> import chai = require('chai');
> import chaiAsPromised = require('chai-as-promised');
> chai.use(chaiAsPromised);
> 
> const expect = chai.expect;
> ```
> 
> The `var chaiAsPromised = require('chai-as-promised')` syntax tells the compiler that the module in question does not have any type definitions. Because of that, `chai-as-promised` types are never registered, and the compiler correctly complains that `Property 'eventually' does not exist on type 'Assertion'`, as both `eventually` and `rejected` are defined in the `chai-as-promised` module which has been ignored.
> 
> Hope this helps!
> Jan

Thanks !!
Finally i solved the problem.
I would like to share the link.
https://stackoverflow.com/a/55855503/5708097

**Comment by jan-molak** [comment]
Cool, glad we could help 👍
