### ISSUE TITLE
Serenity JS angular non angular handling

### ISSUE THREAD

**Issue by AbhineetSharmax** [jan-molak/serenity-js#301]
Hi Jan-molak,
Greetings!

I have a situation where i need to automate a webpage like -

first page is nonangular page (desynchronization) which consist of a iframe (angular synchronization) where SPA loads.

once scenario 1 completes, again have to come out of i frame and have to set UseAngular.desynchronize() to work with non angular page. Do we have beforeeach in serenity?  Please help..

**Comment by jan-molak** [comment]
Hey @AbhineetSharmax! Have a look at [this article](https://janmolak.com/cross-application-testing-with-serenity-js-4103a272b75b) and let me know if it helps?

Serenity itself doesn't have beforeEach, because that's the responsibility of the test runner invoking Serenity - you could use Cucumber [Backgrounds](https://github.com/cucumber/cucumber-js/blob/master/features/background.feature), [before/after hooks](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md), or [onPrepare](https://github.com/angular/protractor/blob/ed955e56a839d7f69da43acb6755763220d3681d/spec/onPrepareConf.js) from Protractor.

**Comment by AbhineetSharmax** [comment]
Thank you jan , using Backgrounds in features. really helpful :)
