### ISSUE TITLE
cant find the REST classes in my install

### ISSUE THREAD

**Issue by scaddenp** [jan-molak/serenity-js#311]
I followed the tutorials to get npm up and running with serenity-cucumber and so far so good, till I tried to use REST. On github, I see serenity-js/rest but this is missing from node-modules.

import {CallAnApi} from 'serenity-js/rest'; doesnt work when it looks like it should to me... I am completely new to npm. Have I missed something?

**Comment by jan-molak** [comment]
Hi @scaddenp!

Serenity/JS uses [Lerna](https://lernajs.io/) to manage the different modules of the framework.
The folders you see under [/packages](https://github.com/jan-molak/serenity-js/tree/master/packages) represent those modules, with `rest` being one of them.
You'll notice that each one of those modules contains `package.json` - a module descriptor. The name under which a given module is published is configured in this file.

For example, the [`rest` module](https://github.com/jan-molak/serenity-js/tree/master/packages/rest) is published to npm as [`@serenity-js/rest`](https://www.npmjs.com/package/@serenity-js/rest).

This means that in order to use it you first need to install it:
```
npm install --save-dev @serenity-js/rest
```

And then import it in your code:
```typescript
import { CallAnApi } from '@serenity-js/rest';
```

Does this help?

**Comment by scaddenp** [comment]
Thanks very much for that very complete and instructive answer. This helps me better understand the tools I am using.
