### ISSUE TITLE
publish crew consoleOutput to a log file

### ISSUE THREAD

**Issue by abhinaba1080** [jan-molak/serenity-js#345]
Hi Jan,

Crew consoleOutput is dope. It will be great if this output can be logged to an external file. 

Do we alteady have something similar in Serenity 1.x? 

If yes, does it also take care logging while parallel execution?

**Comment by jan-molak** [comment]
Hey @abhinaba1080 - have a look at the [`StreamReporter`](https://github.com/jan-molak/serenity-js/blob/2.0/packages/core/src/stage/crew/stream-reporter/StreamReporter.ts) from v2, which should be easy to backport to 1.x. It basically pumps all the domain events it receives to a file, so I guess that's pretty much what you're after?

Parallel execution might be a bit tricky, since Protractor (I'm assuming that's what you're referring to?) spawns a separate process for each test executor. This means that if you wanted all the executors to write to a single file you might end up with a corrupted log. 

To work around that you could produce a separate log file per executor:

```typescript
import { serenity, StreamReporter } form '@serenity-js/core';
import fs = require('fs');

new StreamReporter(fs.createWriteStream(`./events-${ process.pid }.ndjson`));
```

Does this help?

**Comment by abhinaba1080** [comment]
Hi jan,

I am getting below error:

![image](https://user-images.githubusercontent.com/23141842/64978748-da14b500-d8d3-11e9-9f09-0416877fd920.png)

package.json:

 "@serenity-js/core": "^1.6.0",

**Comment by jan-molak** [comment]
Hey @abhinaba1080 - [`StreamReporter`](https://github.com/jan-molak/serenity-js/blob/2.0/packages/core/src/stage/crew/stream-reporter/StreamReporter.ts) is part of Serenity/JS v2.

```
// package.json
"@serenity-js/core": "next"        (or "2.0.1-alpha.81")
```

**Comment by abhinaba1080** [comment]
Thanks.. it worked!

**Comment by jan-molak** [comment]
Excellent, thanks for letting me know!
