### ISSUE TITLE
this.And throws an error

### ISSUE THREAD

**Issue by marktigno** [jan-molak/serenity-js#35]
I have created a cucumber scenario that has the following lines:
```
Given I am on the Cart page
When I change the quantity of <Title> to <Quantity>
And I click Update cart button
Then I should see <Total> as Total of the item <Title>, <Overall Total> as Overall Total and <Grand Total> as the Grand Total
```

But when I execute the test, it throws an error that is shown on the screenshot:
![capture](https://cloud.githubusercontent.com/assets/13494822/24446301/9661d27a-149f-11e7-84df-263ab6f2e8e5.PNG)

Is this a legit issue or am I missing something? Thanks!

**Comment by jan-molak** [comment]
Hey @marktigno,

I'm guessing you're trying to define a cucumber step def along the lines of:

```typescript
this.And('...', function() {})
```

Try doing this instead:

```typescript
this.Given('...', function() {});
```

Did that help?

**Comment by marktigno** [comment]
Hello @jan-molak,

Yeah I did that by replacing "And" with either "Given", "When" or "Then". But some of our scenarios are written on low-level format which includes "And" and "But".

**Comment by jan-molak** [comment]
I agree that the example scenarios you have provided are UI-focused and low-level.
Because of this, it might seem like using multiple `And`s and `But`s was needed, while in fact it highlights an issue with the abstraction level of the scenario.

Check out this [excellent post](https://cucumber.io/blog/2015/03/24/single-source-of-truth).

Also, please note that the `And` and `But` keywords are just aliases for whatever step has occurred before them - see the [source code](https://github.com/cucumber/cucumber-js/blob/7a8a6d730a5aa378a0a0b69a3f5f0fe58473759c/src/keyword_type.js#L17).
