### ISSUE TITLE
Get the report with screenshots without implementing Screenplay Pattern

### ISSUE THREAD

**Issue by magdalenaBartkowiakJowsa** [jan-molak/serenity-js#357]
Hello @jan-molak , is it possible to have screenshots in the report without implementing Sceenplay Pattern? Serenity report is generated but withouts screenshots, Below examplary step implementation:

```javascript
Given('I click Global Careers from the Menu', async () => {
     await WaitFunctions.waitForElementToBeDisplayed(homepage.mainMenu);
     return homepage.openCareerPage();
});
```

If implementing Screenplay Pattern is necessary, would it be possible to use my custom methods inside Tasks/use them as Actions?

i.e. 
```
export const ClickGlobalCareers = () =>
    Task.where(`#actor click Global Careers from main menu`,
        await WaitFunctions.waitForElementToBeDisplayed(homepage.mainMenu);
       return homepage.openCareerPage();
});
```
results in error: Argument of type Promise<void> is not assignable to patameter of type "Activity".

Thank you !

**Comment by jan-molak** [comment]
Hi @magdalenaBartkowiakJowsa!

Yes, you can use Serenity/JS reporting without implementing the Screenplay Pattern. In fact, that's typically what happens as the first step towards implementing it :-)

If you've only just started with Serenity/JS, I'd suggest you go with Serenity/JS version 2  as it has improved both the reporting and Cucumber support (v1 supported only Cucumber 1.x, while v2 supports Cucumber 1.x-6.x). Serenity/JS version 2 is currently in "alpha", but with a stable API and about to become a "proper" release when I'm done writing the docs.

I'm guessing you're using Cucumber with Protractor? If that's the case, then please have a look at [this template implementation](https://github.com/serenity-js/serenity-js-cucumber-protractor-template).

The template would look pretty much the same in a non-Screenplay version, you'd simply have [steps](https://github.com/serenity-js/serenity-js-cucumber-protractor-template/blob/master/features/step_definitions/super_calculator.steps.ts) like:

```typescript
import { Given } from 'cucumber';
import { protractor } from 'protractor';

Given(/I decide to use the Super Calculator/, async function () {
    await protractor.browser.get('/protractor-demo/');
});
```

instead of the Screenplay-style steps like:

```typescript
import { Given } from 'cucumber';
import { WithStage } from '@serenity-js/core';
import { Navigate } from '@serenity-js/protractor';

Given(/(.*) decides to use the Super Calculator/, function (this: WithStage, actorName: string) {
    return this.stage.theActorCalled(actorName).attemptsTo(
        Navigate.to('/protractor-demo/'),
    );
});
```

Now, to answer your second question.

Your implementation is very close to being correct. You'd simply need to replace the low-level Protractor API calls with a list of their [Screenplay equivalents](https://github.com/jan-molak/serenity-js/tree/2.0/packages/protractor/src/screenplay):

```typescript

import { Click, Wait, Target, isDisplayed } form '@serenity-js/protractor';
import { Task } from '@serenity-js/core';
import { by } from 'protractor';

// this is a Screenplay-style "Page Object", describes structure but not the behaviour
class HomePage {
    static mainMenu = Target.the(`main menu`).located(by.css('header nav'));
}

// this is a Screenplay Task - describes the behaviour
export const ViewGlobalCareers = () =>
    Task.where(`#actor views Global Careers`,
        Wait.until(HomePage.mainMenu, isDisplayed()),
        Click.on(HomePage.mainMenu),
    );
```

Hope this helps!
Jan

**Comment by magdalenaBartkowiakJowsa** [comment]
It helped a lot, thank you for your answer @jan-molak !

**Comment by jan-molak** [comment]
I'm glad it helped! 

Pozdrawiam,
Janek 😉
