### ISSUE TITLE
How do I ask a question in a task?

### ISSUE THREAD

**Issue by nbarrett** [jan-molak/serenity-js#57]
Hey @jan-molak - here's something that is stumping me now I am using Serenity in javascript rather than java....

I need to be able ask a question within a task as I need to perform actions based on what I find in the question data (aka: answer). In Java I would normally say `<Question>.answeredBy(actor) -> <data>`, however in the serenity-js I see we pass a different actor interface into the Task:

 `performAs(actor: PerformsTasks):`

as opposed to the question...

 `answeredBy(actor: UsesAbilities):`

So within my task, I'm getting this problem:

![image](https://cloud.githubusercontent.com/assets/626941/26779548/b139f83e-49dd-11e7-95c3-fbd0aa33b15e.png)

I did see in the [serenity source](https://github.com/jan-molak/serenity-js/blob/master/packages/serenity-js/src/serenity/screenplay/interactions/compare_notes.ts#L13) this kind of magic  `performAs(actor: UsesAbilities & AnswersQuestions): PromiseLike<void>`, but I was unable to decipher whether this treatment is applicable to the problem above.  Any thoughts please?

PS: Thanks for helping us all learn typescript as well as the awesome serenity-js!

**Comment by marktigno** [comment]
Try to use this:
`performAs(actor: PerformsTasks): PromiseLike<void> {`
`    return actor.attemptsTo(`
`    See.if(ClassWithQuestion.StaticQuestion, SomeLambdaVar => expect(SomeLambdaVar).to.eventually.equal(ExepecterVar))`
`    );`
`}`

**Comment by nbarrett** [comment]
Cheers for response @marktigno  - actually, I don't want to perform an expectatikon here, so after some experimentation I think I something like:

```
performAs(actor: PerformsTasks & AnswersQuestions): PromiseLike<void> {
        actor.toSee(<Question>).map(data => {
... do some stuff
        });
    }
```
but still not entirely sure 😄

**Comment by nbarrett** [comment]
Actually, that didn't work... , I ended up used the following approach (return actor.attemptsTo() was just to appease the compiler so I could run it):

    performAs(actor: PerformsTasks & AnswersQuestions): PromiseLike<void> {
        actor.toSee(ClassWithQuestion.StaticQuestion).forEach(data => console.log(data));
        return actor.attemptsTo()
    }

But I received: `TypeError: actor.toSee(...).forEach is not a function`. I'm not surprised here as I would have expected .toSee() to have returned a promise but apparently it returns that actual type which doesn't make sense at all! 😖

**Comment by jan-molak** [comment]
Hey @nbarrett,

The regular Serenity/JS [Actor](https://github.com/jan-molak/serenity-js/blob/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/src/serenity/screenplay/actor.ts#L42) `PerformsTasks, UsesAbilities` and `AnswersQuestions`.

Saying `performAs(actor: PerformsTasks & AnswersQuestions)` means "I need an object that implements both those interfaces", so if you want to ask a question inside a task you can definitely use that.

Now regarding the second part of your question (no pun intended ;-) ).

The below construct won't behave the way you'd like it to. That's because `actor.toSee()` will just "spawn" a promise, but won't wait for it. Also, `toSee` returns a promise not a list, so `forEarch` is not suitable here.

```typescript
performAs(actor: PerformsTasks & AnswersQuestions): PromiseLike<void> {
    actor.toSee(ClassWithQuestion.StaticQuestion).forEach(data => console.log(data));
    return actor.attemptsTo()
}
```

What I think you wanted to do is either something along those lines, using the [`See`](https://github.com/jan-molak/serenity-js/blob/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/src/serenity/screenplay/interactions/see.ts) (there's an example of that in the [Journey Planner demo](https://github.com/serenity-js/tutorial-journey-planner/blob/b8c62d96f4edf5711eeb8bc354d3642d0b7b4262/src/journey_planner/check.ts)):

```typescript
performAs(actor: PerformsTasks & AnswersQuestions): PromiseLike<void> {
    return actor.attemptsTo(
        // some tasks
        See.if(ClassWithQuestion.StaticQuestion, someAssertion)
        // some more tasks
    );
}
```

The above is useful if you need an intra-flow check.

Alternatively, if you want to use the value returned by the question, you can do something like this (here's an [example](https://github.com/jan-molak/serenity-js/blob/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/spec/api/screenplay/abilities/take_notes.spec.ts#L43)):

```typescript
performAs(actor: PerformsTasks & AnswersQuestions): PromiseLike<void> {
    return actor.attemptsTo(
        TakeNote.of(ClassWithQuestion.StaticQuestion),
        // ... other tasks
        CompareNotes.toSeeIf(ClassWithQuestion.SomeOtherQuestion, equals, ClassWithQuestion.StaticQuestion)
    );
}
```

Does this help?

Jan

**Comment by nbarrett** [comment]
Hi @jan - thanks for comprehensive response. Actually that's not quite what I want to do as there are no expectations to perform in my use-use. I just want to do something like this:

```
ExtractValue.of(ClassWithQuestionReturningArrayOfMyDomainType.StaticQuestion)
.then(domainItem => RunSomeTasksBasedOnContent.of(domainItem))
```

It might be worth explaining at this point that I'm writing some production code to create some integration with a web-ui which has no API grrrr 😠 , hence the absence of expectation code..

**Comment by jan-molak** [comment]
Ah right, screen scraping, huh? 😉 

I think you might need a custom task for that as there's no support for logical branching I'm afraid.

You'll probably need a construct like this:

```typescript
Check.if(/* question<T> */, verification: (value: T) => boolean).andIfSo(/* list of tasks */).otherwise(/* some other tasks */)
```

For example:

```typescript
Check.if(Text.of(H1), (text: string) => text === 'About us').andIfSo(task1, task2, task3).otherwise(task4, task5);
```

**Comment by nbarrett** [comment]
Yup no REST for the wicked, so resorting to scrape :-) FYI, there is not logical branching required in my use case. I pass the entire `domainItem[]` to my Top level task and then I do the necessary with them in there. So my problem is solely to unconditionally extract the value from my question and off I go...

**Comment by nbarrett** [comment]
So.... I remain stuck on this one @jan-molak and I have to say a little confused.

In previous comments you said actor.toSee() :
-  will just "spawn" a promise, but won't wait for it. 
- returns a promise not a list, so forEach is not suitable here.

When I look at the interface for AnswersQuestions I see:

```{
    toSee<T>(question: Question<T>): T;
}
```

Cool, so all I have to do to extract the data is to call `.then()` on `T` and I get my data? 
It seems not as the type system is adamant that `T` is already resolved so  I'm not sure what to do. In the old days before Typescript, I'd have just slapped .then() on the end and hey presto ... but what do I do now?

**Comment by jan-molak** [comment]
Right, maybe I misunderstood what you wanted to accomplish.

Have a look at [`See`](https://github.com/jan-molak/serenity-js/blob/7651de2423af9e747a18c7835b9c9cdf1fbfb972/packages/serenity-js/src/serenity/screenplay/interactions/see.ts). I think you might need something similar, maybe along the lines of:

```typescript
    performAs(actor: AnswersQuestions): PromiseLike<void> {
        return actor.toSee(ClassWithQuestion.StaticQuestion).then(resultOfTheQuestion => {
            return actor.attemptsTo(
                SomeOtherTask.thatUses(resultOfTheQuestion)
            );
        });
    }
```

Does that help?

J

**Comment by nbarrett** [comment]
erm... no as the result `T` from toSee is not thenable - see previous comment...

**Comment by jan-molak** [comment]
Gotcha, I think this is caused by the Question interface being defined as:

```typescript
export interface Question<T> {
    answeredBy(actor: UsesAbilities): PromiseLike<T>|T;
}
```

Which should probably become:

```typescript
export interface Question<T> {
    answeredBy(actor: UsesAbilities): T;
}
```

With this change, some questions could be defined as synchronous, so `implements Question<string>` for example, some could be async `implements Question<PromiseLike<string>>`. This should resolve the issue you're seeing.

I'll look into this over the coming days.

**Comment by nbarrett** [comment]
Wahoo! thanks @jan-molak - will look into ASAP 👍
