### ISSUE TITLE
how to use debugger

### ISSUE THREAD

**Issue by DeChrish** [jan-molak/serenity-js#83]
how to use debugger?  Debugging option is available in serenity-js?

**Comment by jdmesalosada** [comment]
Hi DeChrish, I was able to do debugging using these instructions:

https://blogs.msdn.microsoft.com/wushuai/2016/08/24/debug-protractor-script-in-visual-studio-code/


The important things to configure:

"program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
 "args": [ "${workspaceRoot}/protractor.conf.js"

The only thing I noticed is that using the breakpoint the program doesn't stop there, I had to use the debugger statement

<img width="509" alt="debug" src="https://user-images.githubusercontent.com/5983195/29275480-db8bbeae-80d0-11e7-96c2-7a1294e35d9c.png">

**Comment by sebcaps** [comment]
Facing an issue to debug SerentyJs test :  debugger does not stop on breakpoint and having message 'Ignored breakpoint, because generate code is missing. Source mapping issue' (approximative translation...)
I tried many option concerning map file (eg outDir, SourceMap...) but was still unable to debug ...
Do you have any idea ?
Thks

**Comment by jan-molak** [comment]
Hi all,

As you have noticed, putting a breakpoint on line 29 in @jdmesalosada's example won't work, because that line _schedules_ a task to be executed by the actor.

What I'd suggest is to create a custom interaction that [has a breakpoint in it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger), for example:

```typescript
const Debug = () => Interaction.where(`#actor pauses to debug`, actor => {
    debugger;                 // The `debugger` statement invokes any available debugging functionality, such as setting a breakpoint.
    return Promise.resolve(); //  returning an automatically resolved promise to satisfy the Interaction interface
});
```

You can then introduce the `Debug()` Interaction in your flow:

```typescript
actor.attemptsTo(
    Open.browserOn('....'),
    Debug(),
    DoSomethingThatIsBuggy(),
);
```

... and run protractor through a debugger. Here's an [example](https://www.jetbrains.com/help/webstorm/run-debug-configuration-protractor.html) of doing that in WebStorm.

Please let me know if that helps!

Jan

**Comment by sebcaps** [comment]
@jan-molak  your suggestion does the trick. However you need to add a Debug() command ithe code.
I finally added a 'typescript build task' to generate *.js and *.map file before running debug and it allowed me to run debugger in VS Studio code by just adding breakpoint.

**Comment by jan-molak** [comment]
Awesome, thanks for letting me know! Glad it helped.
