### ISSUE TITLE
Can't use {0} without quotes in dynamic selector

### ISSUE THREAD

**Issue by CamiloCode** [jan-molak/serenity-js#93]
I need to pass the just the number value without the quotes but its forcing to do it, otherwise I get an invalid selector issue
```

static validationIDTypeCedula = Target.the('validation id type cedula')
        .located(by.xpath('//p-dropdown[@id='registry_validation_dropdown_idType']//li[{0}]'));
```

**Comment by jan-molak** [comment]
Thanks @CamiloCode. I'm not sure what number value you're referring to. Could you please give me a bit more context? What is the exact output you're looking for and what are you seeing instead?

**Comment by CamiloCode** [comment]
yes, sure.

so lets say I want to use the dynamic selector defined above.

**Comment by jan-molak** [comment]
OK, I see what you mean. `of` requires a `string` argument rather than a `number`, so to accomplish what you're after you'd need to convert the number to a string:

```typescript
ValidationForm.validationIDTypeCedula.of(`${this.id_type}`)
```

then your dynamic selector can remain as is:

```typescript
static validationIDTypeCedula = Target.the('validation id type cedula')
        .located(by.xpath(`//p-dropdown[@id='registry_validation_dropdown_idType']//li[{0}]`));
```

Having said that, there's no good reason why `of` should not accept both `strings` _and_ `numbers`. I'll change that in the next version of Serenity/JS

**Comment by CamiloCode** [comment]
@jan-molak thanks ! ill test it
